### ISSUE TITLE
iceweasel-uxp.ebuild updates

### ISSUE THREAD

**Issue by ghost** [g4jc/iceweasel-uxp-overlay#2]
This is not really an "issue" - I just wanted to let you know I have a fork of your iceweasel-uxp ebuild in my overlay at https://github.com/djames1/uxp-overlay

Feel free to use any of the changes in your ebuild.

**Comment by g4jc** [comment]
Looks nice, thanks. I've been meaning to do some general cleanup but haven't had time.
I also have a hackish Icedove-UXP ebuild if interested, will need some general cleanup before release.

**Comment by ghost** [comment]
@g4jc Feel free to send that ebuild my way, I would be interested in getting it updated/added to the repo. Didn't mean to close the GitHub issue

**Comment by g4jc** [comment]
Here's the one I was using a few months ago: https://dpaste.org/917y/raw

**Comment by ghost** [comment]
@g4jc Thanks! I got the icedove-uxp ebuild in my repo now.
